---
title: "Julie Won Overpowers Progressive Leadership"
format:
  pdf:
    df-print: kable
    tbl-colwidths: [75,25]
    code-fold: true
    mainfont: "Georgia"
header-includes:
  - \usepackage{graphicx}
  - \usepackage{adjustbox}
  - \usepackage{afterpage}
  - \usepackage{biblatex}
  - \newcommand{\bibsection}{\clearpage\printbibliography}
execute:
  echo: false
jupyter: python3
bibliography: references.bib
---

```{python}
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.iolib.summary2 import summary_col
from statsmodels.stats.outliers_influence import variance_inflation_factor

from shapely import wkt
import matplotlib.patches as mpatches
import colorsys
from matplotlib.colors import to_hex
import contextily as ctx

from utils import make_precinct_counts,make_demo_map,job_cols,race_cols,cols_to_keep,scale_and_cluster,make_edname,map_round_votes,make_pc_map

from tabulate import tabulate
from IPython.display import Markdown

import seaborn as sns
```

```{python}
demo_cluster = pd.read_csv('../../chapter_two/data/occupation_demo_clusters_on_ed.csv')
ed_level = pd.read_csv('../../cc_election_cleaning/occupation_demo_data_feb21.csv')

ed_shapefile = '../../chapter_two/data/nyed_21a/nyed.shp'
ed_gdf = gpd.read_file(ed_shapefile)

full_results = pd.read_csv('../../cc_election_cleaning/election_results_with_vote_sponsor_cluster_FEB13.csv')
jw = full_results[full_results['candidate'] == 'Julie Won']

ae = pd.read_csv('../../cc_election_cleaning/ae_precincts.csv')
av = pd.read_csv('../../cc_election_cleaning/additional_variables.csv')
fwe = pd.read_csv('../data/finance_with_ethnicity.csv')
f_plus = pd.read_csv('../../council_campaign_finance/data/iwrl_plus.csv')
occ_df = pd.read_csv('../../cc_election_cleaning/occupation_election_feb21.csv')

p_cols = [col for col in occ_df.columns if col[-1] == 'p']
wp_cols = [col for col in occ_df.columns if col.startswith("w2") and col.endswith("p")]
wp_cols.remove('w2cop')
to_remove = [ 'w2psp',
 'w2sep',
 'w2npp',
 'w2govp',
 'w2nip']
wp_cols = [col for col in wp_cols if col not in to_remove]
demo_cols = ['nhw21p','nhb21p','h21p','nha21p','cvap21bapp','mhhi21']

jw = gpd.GeoDataFrame(jw,geometry=jw['geometry'].apply(wkt.loads))
jw = jw.set_crs(epsg=2263, allow_override=True)
co_3857 = jw.to_crs(epsg=3857)

aal = pd.read_csv('../../cc_election_cleaning/precincts_leins.csv')
yd = pd.read_csv('../../cc_election_cleaning/yiddish_precincts.csv')
dt = pd.read_csv('../../cc_election_cleaning/degree_type.csv')
all_rounds = pd.read_csv('../../cc_election_cleaning/all_rounds_results/district_26.csv')
```

Julie Won won the primary in Queen's 26th Council district in a tight race against Amit Bagga. Won also won the rank-and-file Working Families Party vote for their endorsement, but the branch's vote was overridden by the central body and the endorsement instead given to Bagga. For Won this was clear insider baseball, Bagga had refused to rebuke De Blasio for the policing of the George Floyd protests and now his reward had come home. Thus the contest pitted the grassroots against the progressive establishment.

## The District

The 26th sits immediately to the South of Tiffany Caban's district, occupying most of Long Island City and portions of Sunnyside and Astoria. It is in the second highest quintile of education, income, and the white transplant ratio, and in the highest quintile of standard deviation for those categories, signaling significant spread.

## The Campaign

The biggest controversy of the campaign was the Working Families Party endorsement of Bagga. In early 2021 the Queens branch of the WFP voted to endorse Julie Won as the #1 candidate, but in February that vote was overridden by the citywide branch which elected to endorse Bagga [@thisis2021]. There was no rule violation in this decision, the local chapters endorsement is one factor in the city chapter's decision to endorse. Nonetheless, it smelled of corruption to the Won campaign. Bagga had a long history of connection to the city Democratic party and the liberal establishment. He served as Anthony Weiner's chief of staff, and then served a long tenure in the De Blasio administration. Crucially for Won's interpretation of events, he was not one of many De Blasio staffers who signed letters denouncing the mayor's handling of the policing of BLM protests in the summer of 2020. For Won, it was this loyalty in a time of turmoil that purchased support for Bagga in the 2021 primary.

The support came strong. Bagga was the recipient of \$142,225 in Indepent Expenditures, coming primarily from the WFP and affiliated organized labor. This put him in the top 15 of all candidates receiving support and almost a full standard deviation above the mean amount received of $68,385. This support included radio and television spots, digital ads, and direct mailers both district wide and to union members. Won received no support from an IE.

In terms of individual donations, however, Won out-raised Bagga \$86,6644 to \$73,179, which led to a post public matching advantage of \$221,042 to \$168,888. Won's fundraising power came in large part from the district's East Asian community. The Python pacakge ethnicolr uses a large surname dataset built from Wikipedia by the computer scientist Steve Skienna to predict fine-grained ethnicity from last names. Using that package on the donor list, and then aggregating by amount given, produces the tables below for the two candidates:

TABLES

Won raised 50k plus from East Asian donors, more than she or Bagga raised from any other ethnic group.